export const REVIEW_STORAGE_KEY = "sow_review_document_v1";

export function buildReviewPayload({
  selectedTopics,
  generatedLessons,
  teacherChecks,
  hardwareRows,
  classSize
}) {
  const totalMinutes = generatedLessons.reduce((sum, lesson) => sum + (lesson.duration || 0), 0);
  const totalHours = (totalMinutes / 60).toFixed(1);
  const subjects = [...new Set(selectedTopics.map((topic) => topic.subject).filter(Boolean))].join(" / ");
  const generatedDate = new Date().toLocaleDateString("en-GB", {
    year: "numeric",
    month: "long",
    day: "numeric"
  });

  const sections = [
    {
      id: "cover",
      title: "Cover Page",
      type: "cover",
      html: buildCoverHtml({
        subjects,
        lessonCount: generatedLessons.length,
        totalHours,
        classSize,
        generatedDate
      })
    }
  ];

  if (teacherChecks.length) {
    sections.push({
      id: "teacher-checks",
      title: "Lecturer Checks",
      type: "teacher-checks",
      html: buildTeacherChecksHtml(teacherChecks)
    });
  }

  sections.push({
    id: "summary",
    title: "Scheme Summary",
    type: "summary",
    html: buildSummaryHtml(generatedLessons)
  });

  sections.push({
    id: "hardware",
    title: "Hardware Recommendations",
    type: "hardware",
    html: buildHardwareHtml(hardwareRows)
  });

  generatedLessons.forEach((lesson) => {
    sections.push({
      id: `lesson-${lesson.lessonNumber}`,
      title: `Lesson ${lesson.lessonNumber}: ${lesson.topic.name}`,
      type: "lesson",
      html: buildLessonHtml(lesson)
    });
  });

  return {
    title: subjects ? `Scheme of Work - ${subjects}` : "Scheme of Work",
    generatedDate,
    sections
  };
}

export function assembleReviewHtml(payload) {
  return payload.sections.map((section) => {
    return `<section class="review-print-section review-type-${escapeHtml(section.type)}" data-section-id="${escapeHtml(section.id)}">${section.html}</section>`;
  }).join("");
}

function buildCoverHtml({ subjects, lessonCount, totalHours, classSize, generatedDate }) {
  return `
    <div class="sow-cover">
      <div class="cover-logo-row">
        <img src="assets/matrix%20light.png" alt="Matrix TSL" class="cover-logo">
      </div>
      <h1 class="cover-title">Scheme of Work</h1>
      <p class="cover-subject">${escapeHtml(subjects || "Engineering")}</p>
      <div class="cover-meta">
        <div class="cover-meta-item"><span class="cover-meta-label">Lessons</span><span class="cover-meta-value">${lessonCount}</span></div>
        <div class="cover-meta-item"><span class="cover-meta-label">Total Hours</span><span class="cover-meta-value">${totalHours}</span></div>
        <div class="cover-meta-item"><span class="cover-meta-label">Class Size</span><span class="cover-meta-value">${classSize}</span></div>
        <div class="cover-meta-item"><span class="cover-meta-label">Date</span><span class="cover-meta-value">${escapeHtml(generatedDate)}</span></div>
      </div>
      <div class="cover-about">
        <h2>About This Scheme of Work</h2>
        <p>This Scheme of Work has been generated using the Matrix TSL Scheme of Work Generator. It is fully customised to the selected topics, lesson durations, and class size specified by the lecturer.</p>
        <p>Each lesson pack contains structured content aligned to Matrix TSL engineering curricula, including learning outcomes, teacher-led explanation notes, student practice activities, and assessment tasks.</p>
        <p>Matrix TSL provides industry-leading engineering education resources, hardware kits, and digital tools for further and higher education providers across the UK and internationally.</p>
      </div>
      <div class="cover-footer">
        <p>Generated by Matrix TSL Scheme of Work Generator   <strong>matrixtsl.com</strong></p>
      </div>
    </div>
  `;
}

function buildTeacherChecksHtml(teacherChecks) {
  const cards = teacherChecks.map((entry) => {
    const items = entry.checks.map((check) => `<li>${escapeHtml(check)}</li>`).join("");
    return `
      <article class="lesson-card lecturer-card">
        <strong>Lesson ${entry.lessonNumber}: ${escapeHtml(entry.topicName)}</strong> (${entry.duration} min)
        <ul class="teacher-check-list">${items}</ul>
      </article>
    `;
  }).join("");

  return `
    <h2>Lecturer Checks (Staff Only)</h2>
    <section class="lecturer-checks-section">
      ${cards}
    </section>
  `;
}

function buildSummaryHtml(generatedLessons) {
  const rows = generatedLessons.map((lesson) => {
    const availableBlocks = lesson.blocks.filter((block) => !block.missing).length;
    return `
      <tr>
        <td>${lesson.lessonNumber}</td>
        <td>${escapeHtml(lesson.topic.name)}</td>
        <td>${lesson.duration} min</td>
        <td>${availableBlocks}/${lesson.blocks.length} blocks ready</td>
      </tr>
    `;
  }).join("");

  return `
    <h2>Scheme of Work Summary</h2>
    <div class="table-wrap">
      <table>
        <thead>
          <tr>
            <th>Lesson</th>
            <th>Topic</th>
            <th>Duration</th>
            <th>Content Status</th>
          </tr>
        </thead>
        <tbody>${rows}</tbody>
      </table>
    </div>
  `;
}

function buildHardwareHtml(hardwareRows) {
  if (!hardwareRows.length) {
    return `
      <h2>Hardware Recommendations</h2>
      <p class="muted">No matching hardware recommendations yet.</p>
    `;
  }

  const rows = hardwareRows.map((row) => {
    const imageCell = row.image
      ? `<img src="${escapeHtml(row.image)}" alt="${escapeHtml(row.name)} image" class="hardware-image">`
      : "-";
    return `
      <tr>
        <td class="hardware-image-cell">${imageCell}</td>
        <td>${escapeHtml(row.sku)}</td>
        <td>${escapeHtml(row.name)}</td>
        <td>${escapeHtml(row.matchedTags.join(", "))}</td>
        <td>${row.required}</td>
        <td>${row.owned || 0}</td>
        <td class="to-buy">${row.toBuy}</td>
      </tr>
    `;
  }).join("");

  return `
    <h2>Hardware Recommendations</h2>
    <div class="table-wrap">
      <table>
        <thead>
          <tr>
            <th>Image</th>
            <th>SKU</th>
            <th>Item</th>
            <th>Matched Tags</th>
            <th>Required</th>
            <th>Already Own</th>
            <th>Need To Buy</th>
          </tr>
        </thead>
        <tbody>${rows}</tbody>
      </table>
    </div>
  `;
}

function buildLessonHtml(lesson) {
  const blockHtml = lesson.blocks.map((block, blockIndex) => {
    const maybeImage = blockIndex === 0 && lesson.topic.image
      ? `
        <li class="lesson-image-item">
          <img src="${escapeHtml(lesson.topic.image)}" alt="${escapeHtml(lesson.topic.name)} illustration" class="lesson-image-lesson">
        </li>
      `
      : "";

    return `
      <li class="block-item">
        <div class="block-item-header">
          <span>${escapeHtml(block.name)}</span>
        </div>
        <div class="block-print-content">${block.html}</div>
      </li>
      ${maybeImage}
    `;
  }).join("");

  return `
    <article class="lesson-card student-lesson-card">
      <strong>Lesson ${lesson.lessonNumber}: ${escapeHtml(lesson.topic.name)}</strong> (${lesson.duration} min)
      <ul class="block-list">${blockHtml}</ul>
    </article>
  `;
}

function escapeHtml(value) {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}
